export const jwtConstants = {
  secret: process.env.SECRET,
};

/*
 *** WARNING ***
 ** DO NOT EXPOSE THIS KEY PUBLICLY **
 ** IN A PRODUCTION SYSTEM YOU MUST PROTECT THIS KEY **
 ** USING APPROPRIATE MEASURES SUCH AS **  secrets vault,
 ** SECRETS VAULT, ENVIRONMENT VARIABLES OR CONFIGURATION SERVICE **
 *** WARNING ***
 */
